# Generated by Django 2.2 on 2019-05-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип новости')),
                ('icon', models.CharField(blank=True, max_length=30, null=True, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тип новости',
                'verbose_name_plural': 'Типы новостей',
            },
        ),
        migrations.CreateModel(
            name='RExamNewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя новости')),
                ('content', models.TextField(verbose_name='Содержимое новости')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RExamNews.TypeNews', verbose_name='Тип новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': ' Новости',
            },
        ),
    ]
