# Generated by Django 2.2 on 2019-04-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RExamAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
