# Generated by Django 2.2 on 2019-05-12 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RExamAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='study_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RExamAccounts.StudyGroup', verbose_name='Учебная группа'),
        ),
    ]
